version: "3"
services:
  app:
    container_name: node-app
    build: .
    volumes:
      - ./src:/usr/src/app/src
    command: npm start
    restart: always
    ports:
      - "8080:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
